//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.6

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "Categories")]
pub struct Model {
    #[sea_orm(column_name = "CategoryID", primary_key)]
    pub category_id: i64,
    #[sea_orm(column_name = "Name")]
    pub name: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::product_category_mapping::Entity")]
    ProductCategoryMapping,
    #[sea_orm(has_many = "super::products::Entity")]
    Products,
}

impl Related<super::product_category_mapping::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ProductCategoryMapping.def()
    }
}

impl Related<super::products::Entity> for Entity {
    fn to() -> RelationDef {
        super::product_category_mapping::Relation::Products.def()
    }
    fn via() -> Option<RelationDef> {
        Some(
            super::product_category_mapping::Relation::Categories
                .def()
                .rev(),
        )
    }
}

impl ActiveModelBehavior for ActiveModel {}
