//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.6

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "Cities")]
pub struct Model {
    #[sea_orm(column_name = "CityID", primary_key)]
    pub city_id: i64,
    #[sea_orm(column_name = "CityName")]
    pub city_name: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::shipping_addresses::Entity")]
    ShippingAddresses,
    #[sea_orm(has_many = "super::state_city_mapping::Entity")]
    StateCityMapping,
}

impl Related<super::shipping_addresses::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ShippingAddresses.def()
    }
}

impl Related<super::state_city_mapping::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::StateCityMapping.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
