//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.6

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "Colors")]
pub struct Model {
    #[sea_orm(column_name = "ColorID", primary_key)]
    pub color_id: i32,
    #[sea_orm(column_name = "ColorName")]
    pub color_name: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::product_color_mapping::Entity")]
    ProductColorMapping,
    #[sea_orm(has_many = "super::product_variants::Entity")]
    ProductVariants,
}

impl Related<super::product_color_mapping::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ProductColorMapping.def()
    }
}

impl Related<super::product_variants::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ProductVariants.def()
    }
}

impl Related<super::products::Entity> for Entity {
    fn to() -> RelationDef {
        super::product_color_mapping::Relation::Products.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::product_color_mapping::Relation::Colors.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
