//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.6

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "Countries")]
pub struct Model {
    #[sea_orm(column_name = "CountryID", primary_key)]
    pub country_id: i64,
    #[sea_orm(column_name = "CountryName")]
    pub country_name: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::country_state_mapping::Entity")]
    CountryStateMapping,
    #[sea_orm(has_many = "super::shipping_addresses::Entity")]
    ShippingAddresses,
}

impl Related<super::country_state_mapping::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CountryStateMapping.def()
    }
}

impl Related<super::shipping_addresses::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ShippingAddresses.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
