//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use super::sea_orm_active_enums::DiscountType;
use super::sea_orm_active_enums::Status;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "coupons")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub coupon_id: i64,
    #[sea_orm(unique)]
    pub code: String,
    pub discount_type: DiscountType,
    pub discount_value: i32,
    pub min_order_value_paise: Option<i32>,
    pub usage_limit: Option<i32>,
    pub usage_count: Option<i32>,
    pub status: Option<Status>,
    pub starts_at: DateTimeUtc,
    pub ends_at: Option<DateTimeUtc>,
    pub created_at: Option<DateTimeUtc>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
