//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "coupon_redemptions")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub redemption_id: i64,
    pub coupon_id: i64,
    pub user_id: i64,
    pub order_id: i64,
    pub redeemed_at: Option<DateTimeUtc>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::orders::Entity",
        from = "Column::OrderId",
        to = "super::orders::Column::OrderId",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Orders,
    #[sea_orm(
        belongs_to = "super::users::Entity",
        from = "Column::UserId",
        to = "super::users::Column::UserId",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Users,
    #[sea_orm(
        belongs_to = "super::coupons::Entity",
        from = "Column::CouponId",
        to = "super::coupons::Column::CouponId",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Coupons,
}

impl Related<super::orders::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Orders.def()
    }
}

impl Related<super::users::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Users.def()
    }
}

impl Related<super::coupons::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Coupons.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
