//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use super::sea_orm_active_enums::ScopeType;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "coupon_scope")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub coupon_id: i64,
    pub scope_type: ScopeType,
    pub scope_id: i64,
    pub is_allowlist: i8,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::coupons::Entity",
        from = "Column::CouponId",
        to = "super::coupons::Column::CouponId",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Coupons,
}

impl Related<super::coupons::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Coupons.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
