//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.6

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "Discounts")]
pub struct Model {
    #[sea_orm(column_name = "DiscountID", primary_key)]
    pub discount_id: i32,
    #[sea_orm(column_name = "ProductID")]
    pub product_id: Option<i32>,
    #[sea_orm(
        column_name = "DiscountPercentage",
        column_type = "Decimal(Some((5, 2)))",
        nullable
    )]
    pub discount_percentage: Option<Decimal>,
    #[sea_orm(column_name = "StartDate")]
    pub start_date: Option<Date>,
    #[sea_orm(column_name = "EndDate")]
    pub end_date: Option<Date>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::products::Entity",
        from = "Column::ProductId",
        to = "super::products::Column::ProductId",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Products,
}

impl Related<super::products::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Products.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
