//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.6

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "EventLogs")]
pub struct Model {
    #[sea_orm(column_name = "LogID", primary_key)]
    pub log_id: i32,
    #[sea_orm(column_name = "EventType")]
    pub event_type: String,
    #[sea_orm(column_name = "EventDescription", column_type = "Text", nullable)]
    pub event_description: Option<String>,
    #[sea_orm(column_name = "UserID")]
    pub user_id: Option<i32>,
    #[sea_orm(column_name = "EventTime")]
    pub event_time: DateTimeUtc,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::users::Entity",
        from = "Column::UserId",
        to = "super::users::Column::UserId",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Users,
}

impl Related<super::users::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Users.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
