//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "ExchangeRequests")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub exchange_id: i64,
    pub order_id: i64,
    pub user_id: i64,
    pub order_detail_id: i64,
    pub desired_variant_id: i64,
    pub quantity: i64,
    pub status: String,
    pub reason: String,
    pub replacement_order_id: Option<i64>,
    pub created_at: DateTimeUtc,
    pub received_at: Option<DateTimeUtc>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::order_details::Entity",
        from = "Column::OrderDetailId",
        to = "super::order_details::Column::OrderDetailId",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    OrderDetails,
    #[sea_orm(
        belongs_to = "super::orders::Entity",
        from = "Column::OrderId",
        to = "super::orders::Column::OrderId",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Orders2,
    #[sea_orm(
        belongs_to = "super::orders::Entity",
        from = "Column::ReplacementOrderId",
        to = "super::orders::Column::OrderId",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Orders1,
    #[sea_orm(
        belongs_to = "super::product_variants::Entity",
        from = "Column::DesiredVariantId",
        to = "super::product_variants::Column::VariantId",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    ProductVariants,
    #[sea_orm(
        belongs_to = "super::users::Entity",
        from = "Column::UserId",
        to = "super::users::Column::UserId",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Users,
}

impl Related<super::order_details::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::OrderDetails.def()
    }
}

impl Related<super::product_variants::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ProductVariants.def()
    }
}

impl Related<super::users::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Users.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
