//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "Inventory")]
pub struct Model {
    #[sea_orm(column_name = "InventoryID", primary_key)]
    pub inventory_id: i64,
    #[sea_orm(column_name = "VariantID")]
    pub variant_id: Option<i64>,
    #[sea_orm(column_name = "QuantityAvailable")]
    pub quantity_available: Option<i64>,
    pub quantity_reserved: Option<i32>,
    #[sea_orm(column_name = "ReorderLevel")]
    pub reorder_level: Option<i64>,
    pub updated_at: Option<DateTimeUtc>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::product_variants::Entity",
        from = "Column::VariantId",
        to = "super::product_variants::Column::VariantId",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    ProductVariants,
}

impl Related<super::product_variants::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ProductVariants.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
