//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.6

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "Inventory")]
pub struct Model {
    #[sea_orm(column_name = "InventoryID", primary_key)]
    pub inventory_id: i64,
    #[sea_orm(column_name = "ProductID")]
    pub product_id: Option<i64>,
    #[sea_orm(column_name = "QuantityAvailable")]
    pub quantity_available: Option<i64>,
    #[sea_orm(column_name = "ReorderLevel")]
    pub reorder_level: Option<i64>,
    #[sea_orm(column_name = "SupplierID")]
    pub supplier_id: Option<i64>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::products::Entity",
        from = "Column::ProductId",
        to = "super::products::Column::ProductId",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Products,
    #[sea_orm(
        belongs_to = "super::suppliers::Entity",
        from = "Column::SupplierId",
        to = "super::suppliers::Column::SupplierId",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Suppliers,
}

impl Related<super::products::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Products.def()
    }
}

impl Related<super::suppliers::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Suppliers.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
