//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "InventoryLog")]
pub struct Model {
    #[sea_orm(column_name = "LogID", primary_key)]
    pub log_id: i64,
    #[sea_orm(column_name = "ProductID")]
    pub product_id: i64,
    #[sea_orm(column_name = "ChangeQuantity")]
    pub change_quantity: i64,
    #[sea_orm(column_name = "LogTime")]
    pub log_time: DateTimeUtc,
    #[sea_orm(column_name = "Reason")]
    pub reason: Option<String>,
    pub actor_id: Option<String>,
    pub quantity_before: Option<i64>,
    pub quantity_after: Option<i64>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::products::Entity",
        from = "Column::ProductId",
        to = "super::products::Column::ProductId",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Products,
}

impl Related<super::products::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Products.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
