//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.6

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "NewsletterSubscribers")]
pub struct Model {
    #[sea_orm(column_name = "SubscriberID", primary_key)]
    pub subscriber_id: i32,
    #[sea_orm(column_name = "Email", unique)]
    pub email: String,
    #[sea_orm(column_name = "SubscriptionDate")]
    pub subscription_date: DateTimeUtc,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
