//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "NewsletterCampaigns")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub campaign_id: i64,
    pub subject: String,
    #[sea_orm(column_type = "custom(\"MEDIUMTEXT\")")]
    pub body_text: String,
    pub cta_label: Option<String>,
    pub cta_url: Option<String>,
    pub recipient_count: i32,
    pub success_count: i32,
    pub failure_count: i32,
    pub sent_at: DateTimeUtc,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
