//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.6

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "OrderDetails")]
pub struct Model {
    #[sea_orm(column_name = "OrderDetailID", primary_key)]
    pub order_detail_id: i32,
    #[sea_orm(column_name = "OrderID")]
    pub order_id: Option<i32>,
    #[sea_orm(column_name = "ProductID")]
    pub product_id: Option<i32>,
    #[sea_orm(column_name = "Quantity")]
    pub quantity: Option<i32>,
    #[sea_orm(
        column_name = "Price",
        column_type = "Decimal(Some((10, 2)))",
        nullable
    )]
    pub price: Option<Decimal>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::orders::Entity",
        from = "Column::OrderId",
        to = "super::orders::Column::OrderId",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Orders,
    #[sea_orm(
        belongs_to = "super::products::Entity",
        from = "Column::ProductId",
        to = "super::products::Column::ProductId",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Products,
}

impl Related<super::orders::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Orders.def()
    }
}

impl Related<super::products::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Products.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
