//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "OrderDetails")]
pub struct Model {
    #[sea_orm(column_name = "OrderDetailID", primary_key)]
    pub order_detail_id: i64,
    #[sea_orm(column_name = "OrderID")]
    pub order_id: i64,
    #[sea_orm(column_name = "VariantID")]
    pub variant_id: i64,
    #[sea_orm(column_name = "Quantity")]
    pub quantity: i64,
    #[sea_orm(
        column_name = "Price",
        column_type = "Decimal(Some((10, 2)))",
        nullable
    )]
    pub price: Option<Decimal>,
    pub line_total_minor: i64,
    pub unit_price_minor: i32,
    pub discount_minor: Option<i32>,
    pub tax_minor: Option<i32>,
    pub sku: Option<String>,
    pub title: Option<String>,
    pub line_attrs: Option<Json>,
    pub item_status: String,
    pub cancelled_at: Option<DateTimeUtc>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::exchange_requests::Entity")]
    ExchangeRequests,
    #[sea_orm(has_many = "super::order_inventory_restore_items::Entity")]
    OrderInventoryRestoreItems,
    #[sea_orm(
        belongs_to = "super::orders::Entity",
        from = "Column::OrderId",
        to = "super::orders::Column::OrderId",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Orders,
    #[sea_orm(
        belongs_to = "super::product_variants::Entity",
        from = "Column::VariantId",
        to = "super::product_variants::Column::VariantId",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    ProductVariants,
    #[sea_orm(has_many = "super::return_request_items::Entity")]
    ReturnRequestItems,
}

impl Related<super::exchange_requests::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ExchangeRequests.def()
    }
}

impl Related<super::order_inventory_restore_items::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::OrderInventoryRestoreItems.def()
    }
}

impl Related<super::product_variants::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ProductVariants.def()
    }
}

impl Related<super::return_request_items::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ReturnRequestItems.def()
    }
}

impl Related<super::orders::Entity> for Entity {
    fn to() -> RelationDef {
        super::order_inventory_restore_items::Relation::Orders.def()
    }
    fn via() -> Option<RelationDef> {
        Some(
            super::order_inventory_restore_items::Relation::OrderDetails
                .def()
                .rev(),
        )
    }
}

impl Related<super::return_requests::Entity> for Entity {
    fn to() -> RelationDef {
        super::return_request_items::Relation::ReturnRequests.def()
    }
    fn via() -> Option<RelationDef> {
        Some(
            super::return_request_items::Relation::OrderDetails
                .def()
                .rev(),
        )
    }
}

impl ActiveModelBehavior for ActiveModel {}
