//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.6

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "Orders")]
pub struct Model {
    #[sea_orm(column_name = "OrderID", primary_key)]
    pub order_id: i64,
    #[sea_orm(column_name = "UserID")]
    pub user_id: i64,
    #[sea_orm(column_name = "OrderDate")]
    pub order_date: DateTimeUtc,
    #[sea_orm(column_name = "ShippingAddressID")]
    pub shipping_address_id: i64,
    #[sea_orm(column_name = "TotalAmount", column_type = "Decimal(Some((10, 2)))")]
    pub total_amount: Decimal,
    #[sea_orm(column_name = "StatusID")]
    pub status_id: i64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::order_details::Entity")]
    OrderDetails,
    #[sea_orm(
        belongs_to = "super::order_status::Entity",
        from = "Column::StatusId",
        to = "super::order_status::Column::StatusId",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    OrderStatus,
    #[sea_orm(
        belongs_to = "super::shipping_addresses::Entity",
        from = "Column::ShippingAddressId",
        to = "super::shipping_addresses::Column::ShippingAddressId",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    ShippingAddresses,
    #[sea_orm(
        belongs_to = "super::users::Entity",
        from = "Column::UserId",
        to = "super::users::Column::UserId",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Users,
}

impl Related<super::order_details::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::OrderDetails.def()
    }
}

impl Related<super::order_status::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::OrderStatus.def()
    }
}

impl Related<super::shipping_addresses::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ShippingAddresses.def()
    }
}

impl Related<super::users::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Users.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
