//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.6

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "Orders")]
pub struct Model {
    #[sea_orm(column_name = "OrderID", primary_key)]
    pub order_id: i32,
    #[sea_orm(column_name = "UserID")]
    pub user_id: Option<i32>,
    #[sea_orm(column_name = "OrderDate")]
    pub order_date: DateTimeUtc,
    #[sea_orm(column_name = "ShippingAddress", column_type = "Text", nullable)]
    pub shipping_address: Option<String>,
    #[sea_orm(
        column_name = "TotalAmount",
        column_type = "Decimal(Some((10, 2)))",
        nullable
    )]
    pub total_amount: Option<Decimal>,
    #[sea_orm(column_name = "Status")]
    pub status: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::order_details::Entity")]
    OrderDetails,
    #[sea_orm(
        belongs_to = "super::users::Entity",
        from = "Column::UserId",
        to = "super::users::Column::UserId",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Users,
}

impl Related<super::order_details::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::OrderDetails.def()
    }
}

impl Related<super::users::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Users.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
