//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use super::sea_orm_active_enums::FulfillmentStatus;
use super::sea_orm_active_enums::PaymentStatus;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "Orders")]
pub struct Model {
    #[sea_orm(column_name = "OrderID", primary_key)]
    pub order_id: i64,
    #[sea_orm(unique)]
    pub order_number: Option<String>,
    #[sea_orm(column_name = "PublicOrderRef", unique)]
    pub public_order_ref: String,
    #[sea_orm(column_name = "UserID")]
    pub user_id: i64,
    #[sea_orm(column_name = "OrderDate")]
    pub order_date: DateTimeUtc,
    pub created_at: DateTimeUtc,
    pub cancel_window_ends_at: Option<DateTimeUtc>,
    pub earliest_booking_at: Option<DateTimeUtc>,
    pub pickup_target_at: Option<DateTimeUtc>,
    pub pickup_target_reason: Option<String>,
    pub pickup_target_set_by: Option<String>,
    pub pickup_target_updated_at: Option<DateTimeUtc>,
    #[sea_orm(column_name = "ShippingAddressID")]
    pub shipping_address_id: i64,
    #[sea_orm(
        column_name = "TotalAmount",
        column_type = "Decimal(Some((10, 2)))",
        nullable
    )]
    pub total_amount: Option<Decimal>,
    #[sea_orm(column_name = "StatusID")]
    pub status_id: i64,
    pub payment_status: Option<PaymentStatus>,
    pub payment_method: Option<String>,
    pub currency: Option<String>,
    pub updated_at: Option<DateTimeUtc>,
    pub subtotal_minor: i64,
    pub items_total_minor_before_discount: Option<i64>,
    pub shipping_minor: Option<i64>,
    pub shipping_charge_minor: Option<i64>,
    pub tax_total_minor: Option<i64>,
    pub discount_total_minor: Option<i64>,
    pub items_total_minor_after_discount: Option<i64>,
    pub grand_total_minor: i64,
    pub applied_coupon_id: Option<i64>,
    pub applied_coupon_code: Option<String>,
    pub applied_discount_paise: Option<i32>,
    pub refund_settlement_status: Option<String>,
    pub fulfillment_status: FulfillmentStatus,
    #[sea_orm(unique)]
    pub invoice_id: Option<i64>,
    #[sea_orm(unique)]
    pub invoice_number: Option<String>,
    pub invoice_generated_at: Option<DateTimeUtc>,
    pub invoice_storage_path: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::coupon_redemptions::Entity")]
    CouponRedemptions,
    #[sea_orm(
        belongs_to = "super::coupons::Entity",
        from = "Column::AppliedCouponId",
        to = "super::coupons::Column::CouponId",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Coupons,
    #[sea_orm(
        belongs_to = "super::invoices::Entity",
        from = "Column::InvoiceId",
        to = "super::invoices::Column::InvoiceId",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    Invoices,
    #[sea_orm(has_many = "super::order_details::Entity")]
    OrderDetails,
    #[sea_orm(has_many = "super::order_events::Entity")]
    OrderEvents,
    #[sea_orm(has_many = "super::order_inventory_restore_items::Entity")]
    OrderInventoryRestoreItems,
    #[sea_orm(has_one = "super::order_inventory_restores::Entity")]
    OrderInventoryRestores,
    #[sea_orm(
        belongs_to = "super::order_status::Entity",
        from = "Column::StatusId",
        to = "super::order_status::Column::StatusId",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    OrderStatus,
    #[sea_orm(has_many = "super::payment_intents::Entity")]
    PaymentIntents,
    #[sea_orm(has_many = "super::refund_attempts::Entity")]
    RefundAttempts,
    #[sea_orm(has_many = "super::refunds::Entity")]
    Refunds,
    #[sea_orm(has_many = "super::return_requests::Entity")]
    ReturnRequests,
    #[sea_orm(has_many = "super::shipments::Entity")]
    Shipments,
    #[sea_orm(
        belongs_to = "super::shipping_addresses::Entity",
        from = "Column::ShippingAddressId",
        to = "super::shipping_addresses::Column::ShippingAddressId",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    ShippingAddresses,
    #[sea_orm(
        belongs_to = "super::users::Entity",
        from = "Column::UserId",
        to = "super::users::Column::UserId",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Users,
}

impl Related<super::coupon_redemptions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CouponRedemptions.def()
    }
}

impl Related<super::coupons::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Coupons.def()
    }
}

impl Related<super::invoices::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Invoices.def()
    }
}

impl Related<super::order_events::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::OrderEvents.def()
    }
}

impl Related<super::order_inventory_restore_items::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::OrderInventoryRestoreItems.def()
    }
}

impl Related<super::order_inventory_restores::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::OrderInventoryRestores.def()
    }
}

impl Related<super::order_status::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::OrderStatus.def()
    }
}

impl Related<super::payment_intents::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PaymentIntents.def()
    }
}

impl Related<super::refund_attempts::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::RefundAttempts.def()
    }
}

impl Related<super::refunds::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Refunds.def()
    }
}

impl Related<super::return_requests::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ReturnRequests.def()
    }
}

impl Related<super::shipments::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Shipments.def()
    }
}

impl Related<super::shipping_addresses::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ShippingAddresses.def()
    }
}

impl Related<super::users::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Users.def()
    }
}

impl Related<super::order_details::Entity> for Entity {
    fn to() -> RelationDef {
        super::order_inventory_restore_items::Relation::OrderDetails.def()
    }
    fn via() -> Option<RelationDef> {
        Some(
            super::order_inventory_restore_items::Relation::Orders
                .def()
                .rev(),
        )
    }
}

impl ActiveModelBehavior for ActiveModel {}
