//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.6

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "ProductSizeMapping")]
pub struct Model {
    #[sea_orm(column_name = "ProductID", primary_key, auto_increment = false)]
    pub product_id: i32,
    #[sea_orm(column_name = "SizeID", primary_key, auto_increment = false)]
    pub size_id: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::products::Entity",
        from = "Column::ProductId",
        to = "super::products::Column::ProductId",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Products,
    #[sea_orm(
        belongs_to = "super::sizes::Entity",
        from = "Column::SizeId",
        to = "super::sizes::Column::SizeId",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Sizes,
}

impl Related<super::products::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Products.def()
    }
}

impl Related<super::sizes::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Sizes.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
