//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "ProductAttributeMapping")]
pub struct Model {
    #[sea_orm(column_name = "ProductID", primary_key, auto_increment = false)]
    pub product_id: i64,
    #[sea_orm(column_name = "AttributeID", primary_key, auto_increment = false)]
    pub attribute_id: i64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::product_attributes::Entity",
        from = "Column::AttributeId",
        to = "super::product_attributes::Column::AttributeId",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    ProductAttributes,
    #[sea_orm(
        belongs_to = "super::products::Entity",
        from = "Column::ProductId",
        to = "super::products::Column::ProductId",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Products,
}

impl Related<super::product_attributes::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ProductAttributes.def()
    }
}

impl Related<super::products::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Products.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
