//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.6

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "ProductAttributes")]
pub struct Model {
    #[sea_orm(column_name = "AttributeID", primary_key)]
    pub attribute_id: i64,
    #[sea_orm(column_name = "ProductID")]
    pub product_id: Option<i64>,
    #[sea_orm(column_name = "AttributeName")]
    pub attribute_name: Option<String>,
    #[sea_orm(column_name = "AttributeValue")]
    pub attribute_value: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::product_attribute_mapping::Entity")]
    ProductAttributeMapping,
    #[sea_orm(
        belongs_to = "super::products::Entity",
        from = "Column::ProductId",
        to = "super::products::Column::ProductId",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Products,
}

impl Related<super::product_attribute_mapping::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ProductAttributeMapping.def()
    }
}

impl Related<super::products::Entity> for Entity {
    fn to() -> RelationDef {
        super::product_attribute_mapping::Relation::Products.def()
    }
    fn via() -> Option<RelationDef> {
        Some(
            super::product_attribute_mapping::Relation::ProductAttributes
                .def()
                .rev(),
        )
    }
}

impl ActiveModelBehavior for ActiveModel {}
