//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "ProductVariants")]
pub struct Model {
    #[sea_orm(column_name = "VariantID", primary_key)]
    pub variant_id: i64,
    #[sea_orm(column_name = "ProductID")]
    pub product_id: i64,
    #[sea_orm(column_name = "SizeID")]
    pub size_id: Option<i64>,
    #[sea_orm(column_name = "ColorID")]
    pub color_id: Option<i64>,
    #[sea_orm(column_name = "AdditionalPrice")]
    pub additional_price: Option<i32>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::cart::Entity")]
    Cart,
    #[sea_orm(
        belongs_to = "super::colors::Entity",
        from = "Column::ColorId",
        to = "super::colors::Column::ColorId",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Colors,
    #[sea_orm(has_many = "super::inventory::Entity")]
    Inventory,
    #[sea_orm(has_many = "super::inventory_log::Entity")]
    InventoryLog,
    #[sea_orm(has_many = "super::order_details::Entity")]
    OrderDetails,
    #[sea_orm(
        belongs_to = "super::products::Entity",
        from = "Column::ProductId",
        to = "super::products::Column::ProductId",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Products,
    #[sea_orm(
        belongs_to = "super::sizes::Entity",
        from = "Column::SizeId",
        to = "super::sizes::Column::SizeId",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Sizes,
}

impl Related<super::cart::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Cart.def()
    }
}

impl Related<super::colors::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Colors.def()
    }
}

impl Related<super::inventory::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Inventory.def()
    }
}

impl Related<super::inventory_log::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::InventoryLog.def()
    }
}

impl Related<super::order_details::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::OrderDetails.def()
    }
}

impl Related<super::products::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Products.def()
    }
}

impl Related<super::sizes::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Sizes.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
