//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "Products")]
pub struct Model {
    #[sea_orm(column_name = "ProductID", primary_key)]
    pub product_id: i64,
    #[sea_orm(unique)]
    pub sku: Option<String>,
    #[sea_orm(column_name = "Name")]
    pub name: String,
    #[sea_orm(unique)]
    pub slug: Option<String>,
    #[sea_orm(column_name = "Description", column_type = "Text", nullable)]
    pub description: Option<String>,
    #[sea_orm(
        column_name = "Price",
        column_type = "Decimal(Some((10, 2)))",
        nullable
    )]
    pub price: Option<Decimal>,
    pub price_paise: i32,
    #[sea_orm(column_name = "CategoryID")]
    pub category_id: i64,
    pub fabric: Option<String>,
    pub weave: Option<String>,
    pub occasion: Option<String>,
    #[sea_orm(column_type = "Decimal(Some((3, 1)))", nullable)]
    pub length_meters: Option<Decimal>,
    pub has_blouse_piece: Option<i8>,
    #[sea_orm(column_type = "Text", nullable)]
    pub care_instructions: Option<String>,
    pub product_status_id: Option<i64>,
    pub created_at: Option<DateTimeUtc>,
    pub updated_at: Option<DateTimeUtc>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::product_attribute_mapping::Entity")]
    ProductAttributeMapping,
    #[sea_orm(
        belongs_to = "super::product_categories::Entity",
        from = "Column::CategoryId",
        to = "super::product_categories::Column::CategoryId",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    ProductCategories,
    #[sea_orm(has_one = "super::product_images::Entity")]
    ProductImages,
    #[sea_orm(
        belongs_to = "super::product_statuses::Entity",
        from = "Column::ProductStatusId",
        to = "super::product_statuses::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    ProductStatuses,
    #[sea_orm(has_many = "super::product_variants::Entity")]
    ProductVariants,
    #[sea_orm(has_many = "super::reviews::Entity")]
    Reviews,
    #[sea_orm(has_many = "super::wishlist::Entity")]
    Wishlist,
}

impl Related<super::product_attribute_mapping::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ProductAttributeMapping.def()
    }
}

impl Related<super::product_categories::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ProductCategories.def()
    }
}

impl Related<super::product_images::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ProductImages.def()
    }
}

impl Related<super::product_statuses::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ProductStatuses.def()
    }
}

impl Related<super::product_variants::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ProductVariants.def()
    }
}

impl Related<super::reviews::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Reviews.def()
    }
}

impl Related<super::wishlist::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Wishlist.def()
    }
}

impl Related<super::product_attributes::Entity> for Entity {
    fn to() -> RelationDef {
        super::product_attribute_mapping::Relation::ProductAttributes.def()
    }
    fn via() -> Option<RelationDef> {
        Some(
            super::product_attribute_mapping::Relation::Products
                .def()
                .rev(),
        )
    }
}

impl ActiveModelBehavior for ActiveModel {}
