//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.6

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "ProductImages")]
pub struct Model {
    #[sea_orm(column_name = "ImageID", primary_key)]
    pub image_id: i64,
    #[sea_orm(column_name = "ProductID")]
    pub product_id: i64,
    #[sea_orm(column_name = "ImageBase64", column_type = "custom(\"MEDIUMTEXT\")")]
    pub image_base64: String,
    #[sea_orm(column_name = "AltText")]
    pub alt_text: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::products::Entity",
        from = "Column::ProductId",
        to = "super::products::Column::ProductId",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Products,
}

impl Related<super::products::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Products.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
