//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.6

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "Promotions")]
pub struct Model {
    #[sea_orm(column_name = "PromotionID", primary_key)]
    pub promotion_id: i64,
    #[sea_orm(column_name = "PromotionName")]
    pub promotion_name: String,
    #[sea_orm(column_name = "StartDate")]
    pub start_date: DateTime,
    #[sea_orm(column_name = "EndDate")]
    pub end_date: DateTime,
    #[sea_orm(column_name = "Details", column_type = "Text", nullable)]
    pub details: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
