//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "RefundAttempts")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub attempt_id: i64,
    pub order_id: i64,
    pub payment_intent_id: Option<i64>,
    pub razorpay_payment_id: Option<String>,
    pub amount_requested_paise: i64,
    pub amount_sent_to_gateway_paise: i64,
    pub gateway_refund_id: Option<String>,
    pub status: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub provider_error: Option<String>,
    pub idempotency_key: String,
    pub created_at: DateTimeUtc,
    pub updated_at: DateTimeUtc,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::orders::Entity",
        from = "Column::OrderId",
        to = "super::orders::Column::OrderId",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Orders,
    #[sea_orm(has_many = "super::return_requests::Entity")]
    ReturnRequests,
}

impl Related<super::orders::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Orders.def()
    }
}

impl Related<super::return_requests::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ReturnRequests.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
