//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "ReturnRequests")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub return_id: i64,
    pub order_id: i64,
    pub user_id: i64,
    pub status: String,
    pub reason: String,
    pub created_at: DateTimeUtc,
    pub received_at: Option<DateTimeUtc>,
    pub refund_attempt_id: Option<i64>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::orders::Entity",
        from = "Column::OrderId",
        to = "super::orders::Column::OrderId",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Orders,
    #[sea_orm(
        belongs_to = "super::refund_attempts::Entity",
        from = "Column::RefundAttemptId",
        to = "super::refund_attempts::Column::AttemptId",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    RefundAttempts,
    #[sea_orm(has_many = "super::return_request_items::Entity")]
    ReturnRequestItems,
    #[sea_orm(
        belongs_to = "super::users::Entity",
        from = "Column::UserId",
        to = "super::users::Column::UserId",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Users,
}

impl Related<super::orders::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Orders.def()
    }
}

impl Related<super::refund_attempts::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::RefundAttempts.def()
    }
}

impl Related<super::return_request_items::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ReturnRequestItems.def()
    }
}

impl Related<super::users::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Users.def()
    }
}

impl Related<super::order_details::Entity> for Entity {
    fn to() -> RelationDef {
        super::return_request_items::Relation::OrderDetails.def()
    }
    fn via() -> Option<RelationDef> {
        Some(
            super::return_request_items::Relation::ReturnRequests
                .def()
                .rev(),
        )
    }
}

impl ActiveModelBehavior for ActiveModel {}
