//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "ReturnRequestItems")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub return_id: i64,
    #[sea_orm(primary_key, auto_increment = false)]
    pub order_detail_id: i64,
    pub quantity: i64,
    pub refund_amount_minor: i64,
    pub status: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::order_details::Entity",
        from = "Column::OrderDetailId",
        to = "super::order_details::Column::OrderDetailId",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    OrderDetails,
    #[sea_orm(
        belongs_to = "super::return_requests::Entity",
        from = "Column::ReturnId",
        to = "super::return_requests::Column::ReturnId",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    ReturnRequests,
}

impl Related<super::order_details::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::OrderDetails.def()
    }
}

impl Related<super::return_requests::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ReturnRequests.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
