//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "actor_type")]
pub enum ActorType {
    #[sea_orm(string_value = "customer")]
    Customer,
    #[sea_orm(string_value = "admin")]
    Admin,
    #[sea_orm(string_value = "system")]
    System,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "auth_provider")]
pub enum AuthProvider {
    #[sea_orm(string_value = "email")]
    Email,
    #[sea_orm(string_value = "google")]
    Google,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "coupon_status")]
pub enum CouponStatus {
    #[sea_orm(string_value = "active")]
    Active,
    #[sea_orm(string_value = "inactive")]
    Inactive,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "discount_type")]
pub enum DiscountType {
    #[sea_orm(string_value = "percentage")]
    Percentage,
    #[sea_orm(string_value = "fixed_amount")]
    FixedAmount,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "payment_status")]
pub enum PaymentStatus {
    #[sea_orm(string_value = "pending")]
    Pending,
    #[sea_orm(string_value = "authorized")]
    Authorized,
    #[sea_orm(string_value = "captured")]
    Captured,
    #[sea_orm(string_value = "failed")]
    Failed,
    #[sea_orm(string_value = "needs_review")]
    NeedsReview,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "review_status")]
pub enum ReviewStatus {
    #[sea_orm(string_value = "pending")]
    Pending,
    #[sea_orm(string_value = "approved")]
    Approved,
    #[sea_orm(string_value = "rejected")]
    Rejected,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "scope_type")]
pub enum ScopeType {
    #[sea_orm(string_value = "product")]
    Product,
    #[sea_orm(string_value = "category")]
    Category,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "shipment_status")]
pub enum ShipmentStatus {
    #[sea_orm(string_value = "pending")]
    Pending,
    #[sea_orm(string_value = "awb_assigned")]
    AwbAssigned,
    #[sea_orm(string_value = "label_generated")]
    LabelGenerated,
    #[sea_orm(string_value = "manifest_generated")]
    ManifestGenerated,
    #[sea_orm(string_value = "pickup_scheduled")]
    PickupScheduled,
    #[sea_orm(string_value = "picked_up")]
    PickedUp,
    #[sea_orm(string_value = "in_transit")]
    InTransit,
    #[sea_orm(string_value = "out_for_delivery")]
    OutForDelivery,
    #[sea_orm(string_value = "delivered")]
    Delivered,
    #[sea_orm(string_value = "rto_initiated")]
    RtoInitiated,
    #[sea_orm(string_value = "rto_delivered")]
    RtoDelivered,
    #[sea_orm(string_value = "cancelled")]
    Cancelled,
    #[sea_orm(string_value = "lost")]
    Lost,
    #[sea_orm(string_value = "delayed")]
    Delayed,
    #[sea_orm(string_value = "failed")]
    Failed,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "status")]
pub enum Status {
    #[sea_orm(string_value = "pending")]
    Pending,
    #[sea_orm(string_value = "processed")]
    Processed,
    #[sea_orm(string_value = "failed")]
    Failed,
    #[sea_orm(string_value = "needs_review")]
    NeedsReview,
    #[sea_orm(string_value = "client_verified")]
    ClientVerified,
}
