//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "ShippingAddresses")]
pub struct Model {
    #[sea_orm(column_name = "ShippingAddressID", primary_key)]
    pub shipping_address_id: i64,
    #[sea_orm(column_name = "CountryID")]
    pub country_id: i64,
    #[sea_orm(column_name = "StateID")]
    pub state_id: i64,
    #[sea_orm(column_name = "CityID")]
    pub city_id: i64,
    #[sea_orm(column_name = "Road")]
    pub road: Option<String>,
    #[sea_orm(column_name = "ApartmentNoOrName")]
    pub apartment_no_or_name: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::cities::Entity",
        from = "Column::CityId",
        to = "super::cities::Column::CityId",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Cities,
    #[sea_orm(
        belongs_to = "super::countries::Entity",
        from = "Column::CountryId",
        to = "super::countries::Column::CountryId",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Countries,
    #[sea_orm(has_many = "super::orders::Entity")]
    Orders,
    #[sea_orm(
        belongs_to = "super::states::Entity",
        from = "Column::StateId",
        to = "super::states::Column::StateId",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    States,
}

impl Related<super::cities::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Cities.def()
    }
}

impl Related<super::countries::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Countries.def()
    }
}

impl Related<super::orders::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Orders.def()
    }
}

impl Related<super::states::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::States.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
