//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "ShippingAddresses")]
pub struct Model {
    #[sea_orm(column_name = "ShippingAddressID", primary_key)]
    pub shipping_address_id: i64,
    #[sea_orm(column_name = "UserID")]
    pub user_id: Option<i64>,
    #[sea_orm(column_name = "Country")]
    pub country: String,
    #[sea_orm(column_name = "StateRegion")]
    pub state_region: String,
    #[sea_orm(column_name = "City")]
    pub city: String,
    #[sea_orm(column_name = "PostalCode")]
    pub postal_code: String,
    #[sea_orm(column_name = "Road")]
    pub road: Option<String>,
    #[sea_orm(column_name = "ApartmentNoOrName")]
    pub apartment_no_or_name: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::orders::Entity")]
    Orders,
    #[sea_orm(
        belongs_to = "super::users::Entity",
        from = "Column::UserId",
        to = "super::users::Column::UserId",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Users,
}

impl Related<super::orders::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Orders.def()
    }
}

impl Related<super::users::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Users.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
