//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.6

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "ShippingZones")]
pub struct Model {
    #[sea_orm(column_name = "ZoneID", primary_key)]
    pub zone_id: i64,
    #[sea_orm(column_name = "ZipCode")]
    pub zip_code: i32,
    #[sea_orm(column_name = "Description", column_type = "Text", nullable)]
    pub description: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::shipping_addresses::Entity")]
    ShippingAddresses,
}

impl Related<super::shipping_addresses::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ShippingAddresses.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
