//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.6

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "ShippingMethods")]
pub struct Model {
    #[sea_orm(column_name = "MethodID", primary_key)]
    pub method_id: i32,
    #[sea_orm(column_name = "MethodName")]
    pub method_name: Option<String>,
    #[sea_orm(column_name = "Cost", column_type = "Decimal(Some((10, 2)))", nullable)]
    pub cost: Option<Decimal>,
    #[sea_orm(column_name = "EstimatedDeliveryTime")]
    pub estimated_delivery_time: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
