//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use super::sea_orm_active_enums::Status;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "shipments")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub shipment_id: i64,
    pub order_id: i64,
    pub shiprocket_order_id: Option<String>,
    pub awb_code: Option<String>,
    pub carrier: Option<String>,
    pub status: Option<Status>,
    pub tracking_events: Option<Json>,
    pub created_at: Option<DateTimeUtc>,
    pub delivered_at: Option<DateTimeUtc>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::orders::Entity",
        from = "Column::OrderId",
        to = "super::orders::Column::OrderId",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Orders,
}

impl Related<super::orders::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Orders.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
