//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.6

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "Sizes")]
pub struct Model {
    #[sea_orm(column_name = "SizeID", primary_key)]
    pub size_id: i64,
    #[sea_orm(column_name = "SizeName")]
    pub size_name: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::product_size_mapping::Entity")]
    ProductSizeMapping,
    #[sea_orm(has_many = "super::product_variants::Entity")]
    ProductVariants,
}

impl Related<super::product_size_mapping::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ProductSizeMapping.def()
    }
}

impl Related<super::product_variants::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ProductVariants.def()
    }
}

impl Related<super::products::Entity> for Entity {
    fn to() -> RelationDef {
        super::product_size_mapping::Relation::Products.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::product_size_mapping::Relation::Sizes.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
