//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.6

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "StateCityMapping")]
pub struct Model {
    #[sea_orm(column_name = "ID", primary_key)]
    pub id: i64,
    #[sea_orm(column_name = "StateID")]
    pub state_id: i64,
    #[sea_orm(column_name = "CityID")]
    pub city_id: i64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::cities::Entity",
        from = "Column::CityId",
        to = "super::cities::Column::CityId",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Cities,
    #[sea_orm(
        belongs_to = "super::states::Entity",
        from = "Column::StateId",
        to = "super::states::Column::StateId",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    States,
}

impl Related<super::cities::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Cities.def()
    }
}

impl Related<super::states::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::States.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
