//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.6

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "Suppliers")]
pub struct Model {
    #[sea_orm(column_name = "SupplierID", primary_key)]
    pub supplier_id: i32,
    #[sea_orm(column_name = "Name")]
    pub name: Option<String>,
    #[sea_orm(column_name = "ContactInfo")]
    pub contact_info: Option<String>,
    #[sea_orm(column_name = "Address", column_type = "Text", nullable)]
    pub address: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::inventory::Entity")]
    Inventory,
}

impl Related<super::inventory::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Inventory.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
