//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "UserRoles")]
pub struct Model {
    #[sea_orm(column_name = "RoleID", primary_key)]
    pub role_id: i64,
    #[sea_orm(column_name = "RoleName")]
    pub role_name: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::user_role_mapping::Entity")]
    UserRoleMapping,
    #[sea_orm(has_many = "super::user_roles_mapping::Entity")]
    UserRolesMapping,
}

impl Related<super::user_role_mapping::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UserRoleMapping.def()
    }
}

impl Related<super::user_roles_mapping::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UserRolesMapping.def()
    }
}

impl Related<super::users::Entity> for Entity {
    fn to() -> RelationDef {
        super::user_role_mapping::Relation::Users.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::user_role_mapping::Relation::UserRoles.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
