//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use super::sea_orm_active_enums::AuthProvider;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "Users")]
pub struct Model {
    #[sea_orm(column_name = "UserID", primary_key)]
    pub user_id: i64,
    #[sea_orm(column_name = "Username", unique)]
    pub username: String,
    pub auth_provider: AuthProvider,
    pub password_hash: Option<String>,
    #[sea_orm(unique)]
    pub google_sub: Option<String>,
    #[sea_orm(column_name = "Email", unique)]
    pub email: String,
    pub email_verified: Option<i8>,
    pub email_verified_at: Option<DateTimeUtc>,
    #[sea_orm(column_name = "FullName")]
    pub full_name: Option<String>,
    #[sea_orm(column_name = "Address", column_type = "Text", nullable)]
    pub address: Option<String>,
    #[sea_orm(column_name = "Phone", unique)]
    pub phone: Option<String>,
    pub user_status_id: Option<i64>,
    pub role_id: Option<i64>,
    pub last_login_at: Option<DateTimeUtc>,
    pub marketing_opt_out: Option<i8>,
    #[sea_orm(column_name = "CreateDate")]
    pub create_date: DateTimeUtc,
    pub updated_at: Option<DateTimeUtc>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::cart::Entity")]
    Cart,
    #[sea_orm(has_many = "super::coupon_redemptions::Entity")]
    CouponRedemptions,
    #[sea_orm(has_many = "super::event_logs::Entity")]
    EventLogs,
    #[sea_orm(has_many = "super::orders::Entity")]
    Orders,
    #[sea_orm(has_many = "super::payment_intents::Entity")]
    PaymentIntents,
    #[sea_orm(has_many = "super::reviews::Entity")]
    Reviews,
    #[sea_orm(has_many = "super::sessions::Entity")]
    Sessions,
    #[sea_orm(has_many = "super::shipping_addresses::Entity")]
    ShippingAddresses,
    #[sea_orm(has_many = "super::transactions::Entity")]
    Transactions,
    #[sea_orm(has_many = "super::user_activity::Entity")]
    UserActivity,
    #[sea_orm(
        belongs_to = "super::user_roles::Entity",
        from = "Column::RoleId",
        to = "super::user_roles::Column::RoleId",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    UserRoles,
    #[sea_orm(
        belongs_to = "super::user_statuses::Entity",
        from = "Column::UserStatusId",
        to = "super::user_statuses::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    UserStatuses,
    #[sea_orm(has_many = "super::wishlist::Entity")]
    Wishlist,
}

impl Related<super::cart::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Cart.def()
    }
}

impl Related<super::coupon_redemptions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CouponRedemptions.def()
    }
}

impl Related<super::event_logs::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::EventLogs.def()
    }
}

impl Related<super::orders::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Orders.def()
    }
}

impl Related<super::payment_intents::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PaymentIntents.def()
    }
}

impl Related<super::reviews::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Reviews.def()
    }
}

impl Related<super::sessions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Sessions.def()
    }
}

impl Related<super::shipping_addresses::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ShippingAddresses.def()
    }
}

impl Related<super::transactions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Transactions.def()
    }
}

impl Related<super::user_activity::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UserActivity.def()
    }
}

impl Related<super::user_roles::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UserRoles.def()
    }
}

impl Related<super::user_statuses::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UserStatuses.def()
    }
}

impl Related<super::wishlist::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Wishlist.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
