//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.6

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "UserActivity")]
pub struct Model {
    #[sea_orm(column_name = "ActivityID", primary_key)]
    pub activity_id: i64,
    #[sea_orm(column_name = "UserID")]
    pub user_id: Option<i64>,
    #[sea_orm(column_name = "ActivityType")]
    pub activity_type: String,
    #[sea_orm(column_name = "ActivityTime")]
    pub activity_time: DateTimeUtc,
    #[sea_orm(column_name = "ActivityDetails", column_type = "Text", nullable)]
    pub activity_details: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::users::Entity",
        from = "Column::UserId",
        to = "super::users::Column::UserId",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Users,
}

impl Related<super::users::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Users.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
