//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.6

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "Users")]
pub struct Model {
    #[sea_orm(column_name = "UserID", primary_key)]
    pub user_id: i64,
    #[sea_orm(column_name = "Username")]
    pub username: String,
    #[sea_orm(column_name = "Password")]
    pub password: String,
    #[sea_orm(column_name = "Email", unique)]
    pub email: String,
    #[sea_orm(column_name = "FullName")]
    pub full_name: Option<String>,
    #[sea_orm(column_name = "Address", column_type = "Text", nullable)]
    pub address: Option<String>,
    #[sea_orm(column_name = "Phone")]
    pub phone: Option<String>,
    #[sea_orm(column_name = "CreateDate")]
    pub create_date: DateTimeUtc,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::cart::Entity")]
    Cart,
    #[sea_orm(has_many = "super::event_logs::Entity")]
    EventLogs,
    #[sea_orm(has_many = "super::orders::Entity")]
    Orders,
    #[sea_orm(has_many = "super::product_ratings::Entity")]
    ProductRatings,
    #[sea_orm(has_many = "super::reviews::Entity")]
    Reviews,
    #[sea_orm(has_many = "super::transactions::Entity")]
    Transactions,
    #[sea_orm(has_many = "super::user_activity::Entity")]
    UserActivity,
    #[sea_orm(has_many = "super::user_role_mapping::Entity")]
    UserRoleMapping,
    #[sea_orm(has_many = "super::user_roles_mapping::Entity")]
    UserRolesMapping,
    #[sea_orm(has_many = "super::wishlist::Entity")]
    Wishlist,
}

impl Related<super::cart::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Cart.def()
    }
}

impl Related<super::event_logs::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::EventLogs.def()
    }
}

impl Related<super::orders::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Orders.def()
    }
}

impl Related<super::product_ratings::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ProductRatings.def()
    }
}

impl Related<super::reviews::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Reviews.def()
    }
}

impl Related<super::transactions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Transactions.def()
    }
}

impl Related<super::user_activity::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UserActivity.def()
    }
}

impl Related<super::user_role_mapping::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UserRoleMapping.def()
    }
}

impl Related<super::user_roles_mapping::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UserRolesMapping.def()
    }
}

impl Related<super::wishlist::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Wishlist.def()
    }
}

impl Related<super::user_roles::Entity> for Entity {
    fn to() -> RelationDef {
        super::user_role_mapping::Relation::UserRoles.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::user_role_mapping::Relation::Users.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
