import { forwardAdminGraphql } from "@/lib/admin-graphql-server";

const PRODUCT_ROOTS = [
  "searchCategory",
  "createCategory",
  "updateCategory",
  "deleteCategory",
  "searchProduct",
  "createProduct",
  "updateProduct",
  "deleteProduct",
  "searchProductImage",
  "updateProductImage",
  "deleteProductImage",
  "searchSize",
  "createSize",
  "updateSize",
  "deleteSize",
  "searchColor",
  "createColor",
  "updateColor",
  "deleteColor",
  "searchFabric",
  "createFabric",
  "updateFabric",
  "deleteFabric",
  "searchWeave",
  "createWeave",
  "updateWeave",
  "deleteWeave",
  "searchOccasion",
  "createOccasion",
  "updateOccasion",
  "deleteOccasion",
  "searchProductMood",
  "createProductMood",
  "updateProductMood",
  "deleteProductMood",
  "searchProductMoodMapping",
  "createProductMoodMapping",
  "deleteProductMoodMapping",
  "createProductVariant",
  "updateProductVariant",
  "deleteProductVariant",
  "createInventoryItem",
  "searchInventoryItem",
  "updateInventoryItem",
  "deleteInventoryItem",
  "createInventoryLog",
  "searchInventoryLog",
  "updateInventoryLog",
  "deleteInventoryLog",
  "getPresignedUploadUrl",
  "confirmImageUpload",
  "syncProductImages",
  "shopHighlightMoods",
];

export async function POST(request: Request) {
  return forwardAdminGraphql(request, { allowedRoots: PRODUCT_ROOTS });
}

